services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SERVER_URI: postgres
      SERVER_PORT: 8081
      SERVER_SERVLET_CONTEXT_PATH: /api/v1
      SPRING_APPLICATION_NAME: backend
      SPRING_APPLICATION_ERROR_URI: /error
      POSTGRES_VERSION: latest
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGADMIN_VERSION: latest
      PGADMIN_PORT: 5050
    depends_on:
      - postgres
      - pgadmin
    networks:
        - postgres

  postgres:
    # ... rest of your postgres service configuration


    # ... rest of your pgadmin service configurationpostgres:
    container_name: postgres-container
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: